Add Extended Open Multilingual WordNet (extended_omw)
nltk/nltk_data pull request #180
Opened 2021-12-22 03:49 UTC by ExplorerFreda

add extended open multilingual wordnet: http://compling.hss.ntu.edu.sg/omw/summx.html 
Related issue: https://github.com/nltk/nltk_data/issues/179

2021-12-23 11:19 UTC, tomaarsen requested changes
I believe `make pkg_index` must be ran now, as this will re-build the index.xml to include this `extended_omw`.

I'll leave the rest of the `extemded_omw.xml` file to e.g. @fcbond, who will know if the license, copyright and webpage are correct.

2021-12-23 11:19 UTC, tomaarsen commented on packages/corpora/extended_omw.xml
> +<package id="<corpus_name>" name="Extended Open Multilingual WordNet"
```suggestion
<package id="extended_omw" name="Extended Open Multilingual WordNet"
```

2021-12-23 18:54 UTC, stevenbird commented
Is there a case for disseminating this corpus via nltk_data?

2022-01-03 22:09 UTC, tomaarsen approved these changes

2022-01-06 07:34 UTC, merged