Add bcp47 data for handling language tags
nltk/nltk_data pull request #191
Opened 2022-11-03 10:48 UTC by ekaf

Add databases for handling language tags according to the BCP-47 specification (https://www.rfc-editor.org/bcp/bcp47.html).

This package is necessary for the _bcp47.py_  CorpusReader from PR #3060 in NLTK (https://github.com/nltk/nltk/pull/3060).

2022-12-06 10:51 UTC, tomaarsen requested changes
We should try to fill in the .xml a bit more, I've made some suggestions that may be fitting, but I'd like to hear your thoughts too @ekaf.

2022-12-06 10:51 UTC, tomaarsen commented on packages/corpora/bcp47.xml
> +         license=""
```suggestion
         license="IETF Trust and Unicode Inc."
```
Alternatively we can refer to individual licences.

2022-12-06 10:51 UTC, tomaarsen commented on packages/corpora/bcp47.xml
> +         copyright=""
```suggestion
         copyright="Copyright (c) 2022 IETF Trust and Copyright © 1991-2022 Unicode"
```
Perhaps this? Otherwise we may refer to the individual licences and copyright informations.

2022-12-06 10:51 UTC, tomaarsen commented on packages/corpora/bcp47.xml
> +         webpage=""
```suggestion
         webpage="https://www.rfc-editor.org/rfc/rfc5646.html"
```
Or perhaps https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry?

2022-12-07 08:37 UTC, ekaf commented on packages/corpora/bcp47.xml
> +         license=""
Thanks @tomaarsen , I have added all your suggestions.

2022-12-07 10:13 UTC, tomaarsen approved these changes
Looks great now! I'll merge this. Other than my two last comments, https://github.com/nltk/nltk/pull/3060 is almost ready too. Thanks @ekaf

2022-12-07 10:13 UTC, merged